### ISSUE TITLE
module' object has no attribute 'uutounit'

### ISSUE THREAD

**Issue by osstekz** [jnweiger/inkscape-gears-dev#24]
Using Inkscape 0.91pre4 r13712 on Windows generates the following error:

Traceback (most recent call last):
  File "gears-dev.py", line 742, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "gears-dev.py", line 532, in effect
    unit_factor = self.calc_unit_factor()
  File "gears-dev.py", line 492, in calc_unit_factor
    dialog_units = inkex.uutounit(1.0, self.options.units)
AttributeError: 'module' object has no attribute 'uutounit'

**Comment by Neon22** [comment]
Change to way units are handled. now part of Effect class.
So change required is from:
inkex.uutounit
to
self.uutounit

In this file there are 2 sep locations to make the change.
One is in - calc_unit_factor
and also in - calc_circular_pitch

**Comment by jnweiger** [comment]
@Neon22 thanks, fixed in version 0.9
